updated and fixed goaurum, works on macOS

diff --git a/goaurum b/goaurum
--- a/goaurum
+++ b/goaurum
@@ -3,30 +3,31 @@
 # a 300+ line bodge.
 
 # The one line of code that gets updated.
-au_latestversion="https://github.com/aurumbot/core/archive/v1.0.0-beta.4.zip"
+au_latestversion="v1.0.0-beta.4"
 
 _start() {
-  if [ -e `grep "NAME=\"$1\"" $HOME/.aurumfile` ] ; then echo "$1 not found." ; exit 1 ; fi
+  if [ -z `grep "NAME=\"$1\"" $HOME/.aurumfile` ] ; then echo "$1 not found." ; exit 1 ; fi
   pid=`ps -eo "pid,ucomm" | grep "[0-9]\s$1" | perl -pe 's/^[\s]+//g' | perl -pe 's/[\s].+//g'`
-  if [ ! -e $pid ] ; then echo "$1 appears to be already running at $pid." ; exit 0 ; fi
+  if [ ! -z $pid ] ; then echo "$1 appears to be already running at $pid." ; exit 0 ; fi
   path=`grep "NAME=\"$1\"" $HOME/.aurumfile | perl -pe "s/^NAME=\"$1\":PATH=\"|\"$//g"`
   cd $path
   nohup .$1 &
-  echo "Started up $1."
+  if [ $? -ne 0 ] ; then echo "Failed to start up $1" ; else echo "Started up $1." ; fi
+  cd -
 }
 
 _stop() {
-  if [ -e `grep "NAME=\"$1\"" $HOME/.aurumfile` ] ; then echo "$1 not found." ; exit 1 ; fi
-  pid=`ps -eo "pid,ucomm" | grep "[0-9]\s$1" | perl -pe 's/^[\s]+//g' | perl -pe 's/[\s].+//g'`
-  if [ -e $pid ] ; then echo "$1 is not running." ; exit 1 ; fi
-  kill -9 $pid
+  if [ -z `grep "NAME=\"$1\"" $HOME/.aurumfile` ] ; then echo "$1 not found." ; exit 0 ; fi
+  pid=`ps -eo "pid,ucomm" | grep "[0-9]\s\.$1" | perl -pe 's/^[\s]+//g' | perl -pe 's/[\s].+//g'`
+  if [ -z $pid ] ; then echo "$1 is not running." ; exit 0 ; fi
+  kill -2 $pid
   if [ "$?" -ne "0" ] ; then echo "An error code $? was encountered when attempting to kill the bot."; exit 1 ; fi
   exit 0
 }
 
 _index() {
-  n=`grep "NAME=\"$1\":" $HOME/.aurumfile`
-  if [ ! -e $n ] ; then
+  n=`grep "NAME=\"$1\"" $HOME/.aurumfile`
+  if [ ! -z $n ] ; then
     echo "it appears that $1 already exists."
     echo "would you like to overwrite it?"
     read -e -p "[y/N] " answer
@@ -110,7 +111,7 @@ _init() {
       if [[ `which git` = "" ]] ; then
         pkg install git
       fi
-      if [[ -e `which perl` ]] ; then
+      if [[ -z `which perl` ]] ; then
         pkg install perl
       fi
       if [[ `which wget` = "" ]] & [[ `which curl` = "" ]] ; then
@@ -142,9 +143,9 @@ _init() {
       printf "● \033[1;31m386\033[0m (32 bit intel systems)\n"
       printf "● \033[1;31marmv6l\033[0m (arm systems such as rasperry pis)\n"
       read -e -p "> " answer
-      if [[ `which wget` != "" ]] ; then
+      if [ ! -z `which wget` ] ; then
         wget https://dl.google.com/go/go1.11.linux-$answer.tar.gz
-      elif [[ `which curl` != "" ]] ; then
+      elif [ ! -z `which curl` ] ; then
         curl https://dl.google.com/go/go1.11.linux-$answer.tar.gz -o go1.11.linux-$answer.tar.gz
       else
         echo "You don't appear to have wget or curl. how does that work?"
@@ -152,6 +153,7 @@ _init() {
       fi
       echo "installing go"
       tar -C /usr/local -xzf go1.11.linux-$answer.tar.gz
+      rm go1.11.linux-$answer.tar.gz
       echo "installs complete. use goaurum init to configure a new aurum bot"
     fi
   fi
@@ -162,8 +164,8 @@ _init() {
 _install() {
   echo "You will be guided through the steps to create a new aurum instance."
   echo "What would you like to name the bot?"
-  read -e -p "> " au_name
-  au_name=`echo "$au_name" | perl -pe 's/ /_/g'`
+  read -e -p "> " au_name 
+  au_name=`echo $au_name | perl -pe 's/ /_/g' | perl -pe 's#/$##g'`
   echo "Name set ($au_name)"
   echo "Where would you like to setup the bot? (use ./ for current directory)"
   read -e -p "> " au_path
@@ -171,21 +173,20 @@ _install() {
     echo "It appears the path $au_path/$au_name already exists. Would you like to overwrite it?"
     read -e -p "[y/N]: " answer
     case "$answer" in
-      [yY]*) rm -rf $au_path/$au_name ; mkdir $au_path/$au_name ;  ;;
+      [yY]*) rm -rf $au_path/$au_name ; mkdir -p $au_path/$au_name ; cd $au_path/$au_name ;;
       *) echo "Exiting Program" ; exit 0 ;;
     esac
   else
-    cd $au_path
-    if [ "$?" -ne 0 ] ; then echo "You need to first create $au_path." ; exit 1 ; fi
-    mkdir $au_path/$au_name
+    mkdir -p $au_path/$au_name
+    cd $au_path/$au_name
   fi
   _index $au_name $au_path/$au_name
 
   echo "Setting up directory heirarchy in ${au_path}/${au_name}."
   cd ${au_path}/${au_name}
   mkdir plugins dat dat/logs dat/cfg dat/cfg/aurum
-  touch dat/cfg/aurum/preferences.json
-  echo "Heirarchy created.\n"
+  touch ./dat/cfg/aurum/preferences.json
+  echo "Heirarchy created."
   echo "Go to https://discordapp.com/developers/applications/ and create a bot application."
   read -e -p "Enter the Client ID             : " au_cid
   read -e -p "Enter the Client Secret         : " au_sec
@@ -195,10 +196,11 @@ _install() {
   echo "Prefrences set."
   echo "Fetching most recent version of aurum"
   mkdir ./.tmp
-  if [ -e `which git` ] ; then
-    git clone https://github.com/aurumbot/core.git ./.tmp/
+  if [ ! -z `which git` ] ; then
+    git clone --branch $au_latestversion https://github.com/aurumbot/core.git ./.tmp/
+    if [ "$?" -ne "0" ] ; then echo "Error $? encountered when cloning latest version. Panicing." ; exit 1 ; fi
   else
-    echo "You don't appear to have git. how does that work?"
+    echo "You don't appear to have git. how does that work?" ; exit 1
   fi
     mv ./.tmp/main.go ./
     mv ./.tmp/README.md ./
@@ -218,7 +220,7 @@ _install() {
   "clientID": "$au_cid",
   "secret": "$au_sec",
   "token": "$au_tok",
-  "prefix": "$au_prf"
+  "prefix": "$au_prf",
   "channels": [
     ""
   ],
@@ -237,7 +239,6 @@ JsonEnd
   rm main.go
   rm -rf ./.tmp
   echo "installing $au_name"
-
   echo "$au_name successfully installed Use the link below to put it on your server."
   echo "https://discordapp.com/api/oauth2/authorize?client_id=${au_cid}&permissions=8&scope=bot"
   cd -
