wrote a updater

diff --git a/goaurum b/goaurum
--- a/goaurum
+++ b/goaurum
@@ -2,9 +2,6 @@
 
 # a 300+ line bodge.
 
-# The one line of code that gets updated.
-au_latestversion="v1.0.0"
-
 _start() {
   if [ -z `grep "NAME=\"$1\"" $HOME/.aurumfile` ] ; then echo "$1 not found." ; exit 1 ; fi
   pid=`ps -eo "pid,ucomm" | grep "[0-9]\s.$1" | perl -pe 's/^[\s]+//g' | perl -pe 's/[\s].+//g'`
@@ -48,6 +45,45 @@ _remove() {
     *) echo "Exiting Program" ; exit 0 ;;
   esac
   echo "Successfully removed $1 from the database."
+}
+
+_update() {
+  mkdir $HOME/.autmp
+  cd $HOME/.autmp
+  if [ ! -z "$2" ] ; then
+    git clone --branch $2 https://github.com/aurumbot/core.git
+  else
+    git clone https://github.com/aurumbot/core.git
+  fi
+  if [ "$1" = "--goaurum" ] ; then
+    mkdir auupdate ; chmod +x auupdate
+    cat > auupdate << EOF
+#!/bin/bash
+sleep 5
+rm /usr/local/bin/goaurum
+mv ./goaurum /usr/local/bin/goaurum
+chmod +x /usr/local/bin/goaurum
+EOF
+  echo "Preparing to update goaurum. Note that this may take a bit"
+  echo "It also appears to stop the updater, this is normal. Please wait for"
+  echo "a short while (30 seconds?) for it to update, then try goaurum again."
+  ./auupdate &
+  exit 0
+  fi
+  path=`grep "NAME=\"$1\"" $HOME/.aurumfile | perl -pe "s/^NAME=\"$1\":PATH=\"|\"$//g"`
+  if [ -z "$path" ] ; then
+    echo "$1 not found."
+    exit 1
+  fi
+  _stop $1 > /dev/null 2>&1
+  rm $path/.$1
+  env CGO_ENABLED=1 GO111MODULE=on go build -o $path/.$1 ./main.go
+  if [ "$?" -ne "0" ] ; then exit 1 ; else echo "Successfully updated $1." ; fi
+}
+
+_goaurumupdatefinalize() {
+  rm -rf $HOME/.autmp > /dev/null 2>&1
+  echo "Updates installed! (I hope)"
 }
 
 _list() {
@@ -214,7 +250,7 @@ _install() {
     echo "$au_name has been compiled. Finishing up."
     # I'm sorry.
 
-    cat > ./dat/cfg/aurum/preferences.json << JsonEnd
+    cat > ./dat/cfg/aurum/preferences.json << EOF
 {
   "clientID": "$au_cid",
   "secret": "$au_sec",
@@ -230,7 +266,7 @@ _install() {
     ""
   ]
 } 
-JsonEnd
+EOF
   # ok its over.
   rm -rf ./handler
   rm go.mod
@@ -247,19 +283,27 @@ _help() {
   printf "\033[1;31mUsage: \033[1;33mgoaurum <option>
 \033[0mThe config tool and managment tool for aurum discord bots.
 \n\033[1;31mOptions:
-\033[1;32minit                \033[0mfetch system dependancies (golang, perl)
-\033[1;32minstall             \033[0mcreate an instance of aurum
-\033[1;32mstart <name>        \033[0mstart the aurum bot called <name>
-\033[1;32mstop <name>         \033[0mstop the aurum bot called <name>
-\033[1;32mlist                \033[0mlist all aurum instances
-\033[1;32mremove <name>       \033[0mremove the bot <name> from the database
-\033[1;32mindex <name> <path> \033[0madd a pre-existing instance of aurum to 
-                    the manager. Also used to fix broken paths.\n"
+\033[1;32minit                   \033[0mfetch system dependancies (golang, perl)
+\033[1;32minstall                \033[0mcreate an instance of aurum
+\033[1;32mstart <name>           \033[0mstart the aurum bot called <name>
+\033[1;32mstop <name>            \033[0mstop the aurum bot called <name>
+\033[1;32mlist                   \033[0mlist all aurum instances
+\033[1;32mremove <name>          \033[0mremove the bot <name> from the database
+\033[1;32mindex <name> <path>    \033[0madd a pre-existing instance of aurum to 
+                       the manager. Also used to fix broken paths.
+\033[1;32mupdate <bot> [version] \033[0mupdate the <bot> to version [version]. 
+                       use -goaurum to update the goaurum file, leave [version]
+                       blank for the most recent version.\n"
 }
 
 #---------------------------------
-
 touch $HOME/.aurumfile
+
+if [ 0 -ne `ls -l /usr/local/bin/goaurum > /dev/null 2>&1 ; echo $?` ] ; then
+  echo "goaurum needs to be in /usr/local/bin. Move it there and try again."
+  exit 1
+fi
+
 case "$1" in
   "init") _init ;;
   "install") _install ;;
@@ -267,5 +311,6 @@ case "$1" in
   "stop") _stop $2 ;; 
   "list") _list ;;
   "index") _index $2 $3 ;;
+  "update") _update $2 $3 ;;
   *) _help ;;
 esac
